### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/php-src#1]
What's the rationale / reason for MS to do this?

**Comment by weltling** [comment]
Thanks for reaching out. The gap between PHP 5.6 and PHP 7.x is still big, there is a lot of people that couldn't migrate to a newer PHP version yet. Work needs to be done to ensure, that those not yet able to upgrade don't land in an insecure state. Among others, that concerns customers on Azure, too. In keeping with @Microsoft's openness, the needed work is going to be done here and anyone interested is welcome to cooperate. Note - the purpose here are security fixes only, unrelated patches won't be accepted.

Thanks.
