### ISSUE TITLE
PHP 5.6 support duration in Azure

### ISSUE THREAD

**Issue by HBOlsen** [Microsoft/php-src#10]
I'm working with a client who has decided to phase out their PHP apps (Using 5.4.45) before July 2020. Do you know for how long Azure Web Apps will continue to provide support for PHP 5.6 or where I might find more info regarding this matter?

Best regards,
Henrik

**Comment by cmb69** [comment]
I don't think there is any scheduled timeline, but I would assume that PHP 5.6 will be supported for several months at least.
