### ISSUE TITLE
Custom PHP extensions no longer load

### ISSUE THREAD

**Issue by arzanardi** [Microsoft/php-src#11]
Recently, more precisely on Nov 19, 2019, I had a problem where when scaling my application the new instances that scaled no longer found the extensions I use on my system.
Some of my users connected to a given instance could load the system correctly, another part was in error because the extension had not been loaded.
I could even see from phpinfo in both scenarios that the extensions were not loaded.
I spent a few hours having to run my application without scaling and then having no errors. Consequently I had high response time issues.
After a few hours, even instances that were normally loading extensions had the same behavior: they could no longer load extensions.
Anyway, I imagine there was some structure change in the way Azure runs PHP and it wasn't disclosed to us.
I had a similar problem last year, where the "PHP_EXTENSIONS" setting no longer worked when PHP went from 5.6.38 to 5.6.39. From that day I had to implement the configuration "PHP_INI_SCAN_DIR". Since then everything has been working well. But from the 19th, I had the problem that neither of these configurations solved.
I had to move my system to PHP 7 in a hurry and in this case everything worked.
I wonder if you know what may have happened.
Why do these internal Azure updates sometimes generate this kind of behavior?
Is there any way I can protect my environment from this kind of behavior?

**Comment by cmb69** [comment]
Sorry, while this is certainly a valid question, you're asking in the wrong place. I suggest you check out the available [Azure support options](https://azure.microsoft.com/en-us/support/options/). Thanks.
