### ISSUE TITLE
Docker-Images?

### ISSUE THREAD

**Issue by fkaempfer** [Microsoft/php-src#12]
Are there plans/interest in providing docker images from this php fork? Or are there already some? In the latter case it would be great to have a link to one in the README.

Official docker images for PHP 5.6 have not been updated for almost a year now, so docker images build from -for example- php:5.6-apache are probably vulnerable in on form or another.

**Comment by cmb69** [comment]
To my knowledge, there are no plans to provide docker images of this security backport. Sorry. However, [build instructions](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2) are available, so it shouldn't be too hard to roll a docker image.
