### ISSUE TITLE
Q: does this include all the fixes from the Debian-8 package of php 5.6.40 ?

### ISSUE THREAD

**Issue by gggeek** [Microsoft/php-src#13]
I have  hard time finding a single changelog file for the php 5.6.40 package present in Debian Jessie, but it has been maintained at least until to very recently (the changelog link at https://packages.debian.org/jessie/php5 seems broken).
There is info available at https://tracker.debian.org/pkg/php5, but it is split in multiple pages.

What I'd like to know is basically: does this repo include all of the fixes that went into the Debian package? And of course: what are the plans for the future for this repo? How long will it be maintained? And are there plans to produce tagged releases?

**Comment by cmb69** [comment]
This repository is supposed to contain all *security* relevant fixes which have been applied to PHP versions [supported by php.net](https://www.php.net/supported-versions.php). I don't think there is a fixed schedule on the support duration. Tagged releases are [already available](https://github.com/microsoft/php-src/releases).

Thanks.

**Comment by remicollet** [comment]
Additional info: see the NEWS file which have all backported fixes listed.
