### ISSUE TITLE
Bug 72333

### ISSUE THREAD

**Issue by heuri** [Microsoft/php-src#14]
First of all, many thanks for this repository.

Is there anything to be said against applying the fix for bug #72333 (fwrite() on non-blocking SSL sockets doesn't work) to the 5.6 release as well?

Bug: https://bugs.php.net/bug.php?id=72333
Fix: https://github.com/php/php-src/commit/17e9fc9bfeaf575b25782a42937a56e809155858

Thank you very much.

**Comment by cmb69** [comment]
This repository receives only security related fixes. It is maintained for those who have not yet upgraded to [actively supported PHP versions](https://www.php.net/supported-versions.php), and a major concern for us is stability. So no, normal bugs will not be fixed in this repository. Thanks.
