### ISSUE TITLE
Support for openssl-1.1.1?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Microsoft/php-src#15]
thanks.

**Comment by cmb69** [comment]
There is support in the https://github.com/microsoft/php-src/commits/PHP-5.6-security-backports-openssl11 branch. To my knowlegde, this repo is not maintained by Microsoft any longer, though.

**Comment by ROBERT-MCDOWELL** [comment]
it does not seem to compile anymore since openssl-1.1.1k and gcc 11.x

....
/home/src/php-src/ext/openssl/openssl.c:3446:41: warning: ‘DH_generate_parameters’ is depr                                                                                                                                                    ecated [-Wdeprecated-declarations]
 3446 |                                         DH *dhpar = DH_generate_parameters(req->pr                                                                                                                                                    iv_key_bits, 2, NULL, NULL);
      |                                         ^~
In file included from /usr/include/openssl/opensslconf.h:42,
                 from /usr/include/openssl/evp.h:13,
                 from /home/src/php-src/ext/openssl/openssl.c:44:
/usr/include/openssl/dh.h:137:1: note: declared here
  137 | DEPRECATEDIN_0_9_8(DH *DH_generate_parameters(int prime_len, int generator,
      | ^~~~~~~~~~~~~~~~~~
/home/src/php-src/ext/openssl/openssl.c: In function ‘php_openssl_is_private_key’:
/home/src/php-src/ext/openssl/openssl.c:3485:21: error: invalid use of incomplete typedef                                                                                                                                                     ‘EVP_PKEY’ {aka ‘struct evp_pkey_st’}
 3485 |         switch (pkey->type) {
      |                     ^~
/home/src/php-src/ext/openssl/openssl.c:3490:33: error: invalid use of incomplete typedef                                                                                                                                                     ‘EVP_PKEY’ {aka ‘struct evp_pkey_st’}
 3490 |                         if (pkey->pkey.rsa != NULL && (NULL == pkey->pkey.rsa->p |                                                                                                                                                    | NULL == pkey->pkey.rsa->q)) {
      |                                 ^~
/home/src/php-src/ext/openssl/openssl.c:3490:68: error: invalid use of incomplete typedef                                                                                                                                                     ‘EVP_PKEY’ {aka ‘struct evp_pkey_st’}
 3490 |                         if (pkey->pkey.rsa != NULL && (NULL == pkey->pkey.rsa->p |                                                                                                                                                    | NULL == pkey->pkey.rsa->q)) {
      |                                                                    ^~
/home/src/php-src/ext/openssl/openssl.c:3490:97: error: invalid use of incomplete typedef

....

**Comment by dalehhirt** [comment]
This repository is no longer supported for building PHP 5.6 backports for Windows.
