### ISSUE TITLE
Test fixes for Windows QA on PHP 5.6

### ISSUE THREAD

**Issue by weltling** [Microsoft/php-src#2]
To continue provide QA, some tests on Windows platform need to be fixed. Tests need to be fixed in

- PHP-5.6-security-backports, separate PR

Please create pull requests, so the test fixes can be merged as a single squashed commit.

Thanks.

**Comment by weltling** [comment]
@hollyhuili could you check this, please? The backport builds

https://windows.php.net/downloads/snaps/ostc/sec-backports/

Thanks.

**Comment by weltling** [comment]
@hollyhuiLi ping on this :)

Thanks.

**Comment by hollyhuiLi** [comment]
Just want to double confirm what need to be done: should I run all the tests on the backports builds 5.6 and 7.0, collecting the failed tests and fix them? And I can only see 5.6 nts x86, and 7.0 nts x86+x64, is that expected?

**Comment by cmb69** [comment]
This is only about the PHP-5.6-security-backports branch. It seems to me that the builds on https://windows.php.net/downloads/snaps/ostc/sec-backports/ are out-dated. @weltling, shouldn't we have up-to-date builds?

**Comment by cmb69** [comment]
@hollyhuiLi, I just spoke with @weltling: please use the https://windows.php.net/downloads/snaps/ostc/sec-backports/ builds for now.

**Comment by hollyhuiLi** [comment]
Where can I check in the fixes? I assume I have to fork source code then send PR, but to which branch?

**Comment by surfmuggle** [comment]
Under [sec-backports](https://windows.php.net/downloads/snaps/ostc/sec-backports/) lies a.o. this file  [php-5.6.40-nts-Win32-VC11-x86.zip](https://windows.php.net/downloads/snaps/ostc/sec-backports/php-5.6.40-nts-Win32-VC11-x86.zip) (3/27/2019  3:23 PM). The [PHP Manager](https://www.iis.net/downloads/community/2018/05/php-manager-150-for-iis-10) website mentions that the manager can be used to manage PHP installations compatible with the latest version of IIS

1. I could not find a list of IIS 10 compatible PHP version - does such a list exist?
2. I would like to find out if the PHP 5.6.40 file from above runs on windows 2016?     
3. And if there are arguments against using it with IIS 10?

**Comment by cmb69** [comment]
@surfmuggle, this is a pretty old build, and should not be used for production. To my knowledge, there are no plans to publicly distribute pre-built binaries of this repo. Of course, you are free to build your own.

**Comment by dalehhirt** [comment]
Resolved.  Closing issue.
