### ISSUE TITLE
Test fixes for Windows QA on PHP 7.0

### ISSUE THREAD

**Issue by weltling** [Microsoft/php-src#3]
To continue provide QA, some tests on Windows platform need to be fixed. Tests need to be fixed in

- PHP-7.0-security-backports, separate PR

Please create pull requests, so the test fixes can be merged as a single squashed commit.

Thanks.

**Comment by weltling** [comment]
@lavturo could you check this, please? The backport builds

https://windows.php.net/downloads/snaps/ostc/sec-backports/

Thanks.

**Comment by cmb69** [comment]
Fixed with 1e5b7938ff88566dcdb805a2d561a1f8d0e560ad.
