### ISSUE TITLE
PHP 7 Vulnerability Disclosure (2019-087)

### ISSUE THREAD

**Issue by rossbearman** [Microsoft/php-src#8]
A number of vulnerabilities have been [disclosed against PHP 7](https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution_2019-087/).

Issue [#75457](https://bugs.php.net/bug.php?id=75457) in PHP 7.1 appears to be the only one that PHP internals have classified as an actual security issue. Will it be investigated whether this affects 5.6?

**Comment by cmb69** [comment]
The fix has already been committed to this repo: 582128d6b5acdef94752cc4ea4a049497067bb38.

**Comment by rossbearman** [comment]
Thanks for the quick response @cmb69. Presumably, that means the issue does not affect PHP 5.6?

**Comment by cmb69** [comment]
We don't commit fixes for issues that don't affect this repo. :)

**Comment by rossbearman** [comment]
Sorry, my fault, GitHub was defaulting to the `PHP-5.6-security-backports` branch which doesn't show that commit (it's got the last commit as b85766d on 21 May), I didn't catch that it was on the `php-5.6.40-6` tag. Thanks for taking the time.

**Comment by cmb69** [comment]
Oh, indeed, there's something wrong there. https://github.com/microsoft/php-src/commits/PHP-5.6-security-backports is up-to-date, though.
