### ISSUE TITLE
Support for PHP 7.1? (The offical support is ending on 1 Dec 2019)

### ISSUE THREAD

**Issue by ewasser** [Microsoft/php-src#9]
Hello,

thanks for your work to support older PHP versions.

We have here security backports for [PHP 5.6](https://github.com/microsoft/php-src) and [PHP 7.0](https://github.com/microsoft/php-src/tree/PHP-7.0-security-backports). PHP 7.1 has offical Security Support until 1 Dec 2019 ([Source](https://www.php.net/supported-versions.php)).

Do you have plans to support PHP 7.1 with security backports like you support PHP 5.6 and PHP 7.0?

**Comment by cmb69** [comment]
There are no concrete plans for 7.1 security backports *yet*.

**Comment by dalehhirt** [comment]
Closing as not supporting any 7.x or later builds with security backports.
